### ISSUE TITLE
Request to help

### ISSUE THREAD

**Issue by Gani-23** [afkniladri/Acer-Nitro5-Hackintosh-OC#10]
hey mate can you please help me with creation of opencore/clover EFI  for VENTURA 
my configurations are
my contact : saiganesh7989@gmail.com

Device model name:	ACER NITRO 515-52
Processor: 	Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz   2.30 GHz
Installed RAM:	8.00 GB (7.84 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

REALTEK ALC 255 DRIVERS 

500 GIGS -SSD NVME.2 
1 TB HDD - TOSHIBA 
Nvidia GE force GTX - 1050

**Comment by 0xNILADRI** [comment]
Here's the awesome guide I've followed : https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html
And for your dedicated laptop this is the config :  https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake.html#starting-point

Hope this helps.
