### ISSUE TITLE
HDMİ

### ISSUE THREAD

**Issue by TheYigidOS** [afkniladri/Acer-Nitro5-Hackintosh-OC#2]
hi i have acer nitro 5 an515-51  and i want to use hackintosh there ise way to use hdmi and which MacOS versions support gtx1050ti? Thank you

Kind regards...

**Comment by 0xNILADRI** [comment]
High siera supports nvidia 1050ti web drivers. It should work for you , just remove the acpi to diable dgpu.

**Comment by 0xNILADRI** [comment]
And if it works don't forget to ⭐. 😜

**Comment by TheYigidOS** [comment]
> And if it works don't forget to ⭐. 😜

hi which macos version works with only hdmi and QCA61X4A (gtx1050ti doesnt important at all i must use monitor)
does mojave or catalina or big sur supports?

**Comment by 0xNILADRI** [comment]
> > And if it works don't forget to ⭐. 😜
> 
> hi which macos version works with only hdmi and QCA61X4A (gtx1050ti doesnt important at all i must use monitor)
> does mojave or catalina supports?

Please go through the documentation, HDMI port is hardwired to the dgpu so in order to get the hdmi work you need nvidia graphics and yes atheros wifi isnt supported on any version. Only High siera or older for working hdmi !

**Comment by 0xNILADRI** [comment]
Please go through this, https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/blob/master/extras/hardware.md.

**Comment by TheYigidOS** [comment]
THX for your all time

**Comment by 0xNILADRI** [comment]
Mention not!
