### ISSUE TITLE
wifi not working

### ISSUE THREAD

**Issue by Aerstme** [afkniladri/Acer-Nitro5-Hackintosh-OC#3]
Hi

I have an acer nitro 5 an 515-51 565S with gtx 1050 (not the ti version), and the same wifi card as 
I can see in the description of this repository

I installed macos big sur but i cant get the wifi working...I need to buy a wifi usb to get it working?  

thanks for all
regards

**Comment by 0xNILADRI** [comment]
As the readme mentions I'm using  TL-WN725N V3 usb wifi dongle. So you should either buy it or another supported wifi cards check here : https://dortania.github.io/Wireless-Buyers-Guide/unsupported.html , fyi those cards are expensive. Also you can opt for Intel cards, itlwm supports few cards check it out here : https://github.com/OpenIntelWireless/itlwm . Although to be honest not every feature works perfectly. I would recommend you to stick with TP link (mine), cheap and works fine.

**Comment by 0xNILADRI** [comment]
Use different wifi card.
