### ISSUE TITLE
I only have 7MB for VRAM, any ideas?

### ISSUE THREAD

**Issue by devfelipereis** [afkniladri/Acer-Nitro5-Hackintosh-OC#6]

**Comment by 0xNILADRI** [comment]
It means you have no graphics acceleration. Can you provide me the system details ?

**Comment by 0xNILADRI** [comment]
Also I would recommend to use this EFI only if you have the exact same specs as my laptop. If not please use the guide to create your own config.

**Comment by devfelipereis** [comment]
Mine is the Acer Nitro 5 AN515-52BW
i5 8300HQ
GTX1050t

**Comment by 0xNILADRI** [comment]
Exactly. You have different processor. Go to dortania guide do the changes required for your own processor (generation).

**Comment by devfelipereis** [comment]
I fixed it!

Change this:

```
<dict>
    <key>AAPL,ig-platform-id</key>
    <data>AAAbWQ==</data>
</dict>
```

to this:

```
<dict>
    <key>AAPL,ig-platform-id</key>
    <data>AACbPg==</data>
</dict>
```

**Comment by 0xNILADRI** [comment]
Don't forget to 🌟 the repository. 😅
