### ISSUE TITLE
Updating OC to 0.7.8

### ISSUE THREAD

**Issue by Aerstme** [afkniladri/Acer-Nitro5-Hackintosh-OC#7]
Hi 

I would like to know if you can provide a guide to update OpenCore. I need to update macOS to 11.6.2 but I cant since I installed these drivers https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter for the wifi

I dont know what im doing wrong here, but i need to  update the OS version

I already enabled SIP but when the updater looks for new updates it shows anything.

thanks in advance

**Comment by rgvxsthi** [comment]
Hi @Aerstme

I have [created a fork of this project for macOS Big Sur](https://github.com/rgvxsthi/AcerNitro5-Hackintosh-BigSur) (currently running 11.6.4), latest OpenCore 0.7.8 and using the same WiFi driver that you have mentioned above. Do check it and let me know how it goes!

**Comment by 0xNILADRI** [comment]
I was busy so I couldn't resolve the issue. It has been resolved now, thus closing the issue.
